name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install Dependencies
        run: pnpm install

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build Storybook
        run: pnpm build --filter=@antdddddddddd/docs^...

      - name: Copy Storybook to temp directory
        run: cp -r ./apps/docs/storybook-static ../storybook-static-temp

      - name: Switch to gh-pages branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git fetch origin
          git checkout -b gh-pages || git checkout gh-pages

      - name: Clean gh-pages branch
        run: rm -rf *

      - name: Copy Storybook from temp directory
        run: cp -r ../storybook-static-temp/* .

      - name: List files in current directory
        run: ls -al

      - name: Commit and Push changes
        run: |
          git add .
          git commit -m 'Deploy Storybook to GitHub Pages'
          git push origin gh-pages --force


      - name: Send a Slack notification if a publish happens
        if: steps.changesets.outputs.published == 'true'
        run: my-slack-bot send-notification --message "A new version of ${{ github.repository }} was published!"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
